### ISSUE TITLE
yj94说你抄袭，如果借鉴需要标明引用

### ISSUE THREAD

**Issue by YUJI123-HASH** [timwhitez/BinHol#1]
![image](https://github.com/user-attachments/assets/5bee16dc-4c55-4506-a7e8-f1a35ef20fd4)

抄袭项目：https://github.com/yj94/BinarySpy

**Comment by YUJI123-HASH** [comment]
![image](https://github.com/user-attachments/assets/2b7c391f-714c-4986-81a3-9ae379e9ea2b)

**Comment by timwhitez** [comment]
好的，项目写的比较急不好意思，帮我向大佬道歉，已经加上来源
